network:
  _target_: .projects.intentnet.intentnet.IntentNet
  args:
    dev: cuda:0
    sig_nll_weight: 5.0
    lr: 0.0001
    weight_decay: 1e-4
    test_interval: 4
    use_googlenet:
    resume_path: